const schoolList = {
  "schoolList": [ 
    { id: 0, name: 'Academy of Art University' },
    { id: 1, name: 'Art Center College of Design' },
    { id: 2, name: 'Azusa Pacific University' },
    { id: 3, name: 'Bethesda University' },
    { id: 4, name: 'Biola University' },
    { id: 5, name: 'California Institute of Integral Studies' },
    { id: 6, name: 'California Baptist University' },
    { id: 7, name: 'California College of the Arts' },
    { id: 8, name: 'California Institute of Technology' },
    { id: 9, name: 'California Lutheran University' },
    {
      id: 10,
      name: 'California Polytechnic State University-San Luis Obispo'
    },
    { id: 11, name: 'California State University-Bakersfield' },
    { id: 12, name: 'California State University-Stanislaus' },
    { id: 13, name: 'California State University-San Bernardino' },
    { id: 14, name: 'California State Polytechnic University-Pomona' },
    { id: 15, name: 'California State University-Chico' },
    { id: 16, name: 'California State University-Dominguez Hills' },
    { id: 17, name: 'California State University-Fresno' },
    { id: 18, name: 'California State University-Fullerton' },
    { id: 19, name: 'California State University-East Bay' },
    { id: 20, name: 'California State University-Long Beach' },
    { id: 21, name: 'California State University-Los Angeles' },
    { id: 22, name: 'California State University-Northridge' },
    { id: 23, name: 'California State University-Sacramento' },
    { id: 24, name: 'University of California-Berkeley' },
    { id: 25, name: 'University of California-Davis' },
    { id: 26, name: 'University of California-Irvine' },
    { id: 27, name: 'University of California-Los Angeles' },
    { id: 28, name: 'University of California-Riverside' },
    { id: 29, name: 'University of California-San Diego' },
    { id: 30, name: 'University of California-Santa Barbara' },
    { id: 31, name: 'University of California-Santa Cruz' },
    { id: 32, name: 'Sofia University' },
    { id: 33, name: 'California Christian College' },
    { id: 34, name: 'California Institute of the Arts' },
    { id: 35, name: 'California State University Maritime Academy' },
    { id: 36, name: 'Chapman University' },
    { id: 37, name: 'Concordia University-Irvine' },
    { id: 38, name: 'San Diego Christian College' },
    { id: 39, name: 'Claremont McKenna College' },
    { id: 40, name: 'Cogswell College' },
    { id: 41, name: 'Columbia College Hollywood' },
    { id: 42, name: 'Design Institute of San Diego' },
    { id: 43, name: 'Dominican University of California' },
    { id: 44, name: 'Fresno Pacific University' },
    { id: 45, name: 'Golden Gate University-San Francisco' },
    { id: 46, name: 'Harvey Mudd College' },
    { id: 47, name: 'Holy Names University' },
    { id: 48, name: 'Humboldt State University' },
    {
      id: 49,
      name: 'Humphreys University-Stockton and Modesto Campuses'
    },
    { id: 50, name: 'John F. Kennedy University' },
    { id: 51, name: 'American Jewish University' },
    { id: 52, name: 'Life Pacific University' },
    { id: 53, name: 'University of La Verne' },
    { id: 54, name: 'Laguna College of Art and Design' },
    { id: 55, name: 'Lincoln University' },
    { id: 56, name: 'Southern California Seminary' },
    { id: 57, name: 'La Sierra University' },
    { id: 58, name: 'Loma Linda University' },
    { id: 59, name: "The Master's University and Seminary" },
    { id: 60, name: 'Loyola Marymount University' },
    { id: 61, name: 'Menlo College' },
    { id: 62, name: 'Mills College' },
    {
      id: 63,
      name: 'Middlebury Institute of International Studies at Monterey'
    },
    { id: 64, name: "Mount Saint Mary's University" },
    { id: 65, name: 'National University' },
    { id: 66, name: 'Newschool of Architecture and Design' },
    { id: 67, name: 'Notre Dame de Namur University' },
    { id: 68, name: 'Occidental College' },
    { id: 69, name: 'Otis College of Art and Design' },
    { id: 70, name: 'Hope International University' },
    { id: 71, name: 'Palo Alto University' },
    { id: 72, name: 'Pacific Oaks College' },
    { id: 73, name: 'Pacific States University' },
    { id: 74, name: 'Pacific Union College' },
    { id: 75, name: 'University of the Pacific' },
    { id: 76, name: 'Pepperdine University' },
    { id: 77, name: 'Pitzer College' },
    { id: 78, name: 'Point Loma Nazarene University' },
    { id: 79, name: 'Pomona College' },
    { id: 80, name: 'University of Redlands' },
    { id: 81, name: 'Samuel Merritt University' },
    { id: 82, name: 'San Diego State University' },
    { id: 83, name: 'University of San Diego' },
    { id: 84, name: 'San Francisco Art Institute' },
    { id: 85, name: 'San Francisco State University' },
    { id: 86, name: 'University of San Francisco' },
    { id: 87, name: 'William Jessup University' },
    { id: 88, name: 'San Jose State University' },
    { id: 89, name: 'Santa Clara University' },
    { id: 90, name: 'Scripps College' },
    { id: 91, name: 'Shasta Bible College and Graduate School' },
    { id: 92, name: 'Simpson University' },
    { id: 93, name: "Saint Mary's College of California" },
    { id: 94, name: 'Sonoma State University' },
    { id: 95, name: 'Vanguard University of Southern California' },
    { id: 96, name: 'Southern California Institute of Architecture' },
    { id: 97, name: 'University of Southern California' },
    { id: 98, name: 'Thomas Aquinas College' }
  ]
}

exports.schoolList = schoolList;